<?xml version="1.0" encoding="utf-8"?><Database Name="CheckersDB" Class="CheckersDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\CheckersDB.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CheckersDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TblFamily" Member="TblFamilies">
    <Type Name="TblFamily">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="TblFamily_TblFamilyPlayer" Member="TblFamilyPlayers" ThisKey="Id" OtherKey="idFamily" Type="TblFamilyPlayer" />
    </Type>
  </Table>
  <Table Name="dbo.TblPlayerGame" Member="TblPlayerGames">
    <Type Name="TblPlayerGame">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idPlayer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idGame" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TblGame_TblPlayerGame" Member="TblGame" ThisKey="idGame" OtherKey="Id" Type="TblGame" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="TblPlayer_TblPlayerGame" Member="TblPlayer" ThisKey="idPlayer" OtherKey="Id" Type="TblPlayer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblFamilyPlayer" Member="TblFamilyPlayers">
    <Type Name="TblFamilyPlayer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idFamily" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPlayer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TblFamily_TblFamilyPlayer" Member="TblFamily" ThisKey="idFamily" OtherKey="Id" Type="TblFamily" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="TblPlayer_TblFamilyPlayer" Member="TblPlayer" ThisKey="idPlayer" OtherKey="Id" Type="TblPlayer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblGame" Member="TblGames">
    <Type Name="TblGame">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="WinnerPlayerNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TblGame_TblPlayerGame" Member="TblPlayerGames" ThisKey="Id" OtherKey="idGame" Type="TblPlayerGame" />
      <Association Name="TblGame_TblMove" Member="TblMoves" ThisKey="Id" OtherKey="idGame" Type="TblMove" />
    </Type>
  </Table>
  <Table Name="dbo.TblMove" Member="TblMoves">
    <Type Name="TblMove">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idPlayer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idGame" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="From_X" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="From_Y" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="To_X" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="To_Y" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RivalEat" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TblGame_TblMove" Member="TblGame" ThisKey="idGame" OtherKey="Id" Type="TblGame" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="TblPlayer_TblMove" Member="TblPlayer" ThisKey="idPlayer" OtherKey="Id" Type="TblPlayer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblPlayer" Member="TblPlayers">
    <Type Name="TblPlayer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="TblPlayer_TblPlayerGame" Member="TblPlayerGames" ThisKey="Id" OtherKey="idPlayer" Type="TblPlayerGame" />
      <Association Name="TblPlayer_TblFamilyPlayer" Member="TblFamilyPlayers" ThisKey="Id" OtherKey="idPlayer" Type="TblFamilyPlayer" />
      <Association Name="TblPlayer_TblMove" Member="TblMoves" ThisKey="Id" OtherKey="idPlayer" Type="TblMove" />
    </Type>
  </Table>
</Database>